README.md
This adds an icon next to the awesome-math title as described in the [awesome/awesome-manifesto].
This awesome list should probably try and conform to the [awesome/awesome-manifesto] and follow [awesome/create-list]
[awesome/awesome-manifesto]:https://github.com/sindresorhus/awesome/blob/master/awesome.md
[awesome/create-list]:https://github.com/sindresorhus/awesome/blob/master/create-list.md
=> Adds an Awesome icon next to the title

README.md
Add a link to a comprehensive glossary of data modeling.
The original webpage doesn't exist anymore but is still reachable through archive.org.
=> Add a link to a comprehensive glossary of data modeling.

README.md
List of stats papers http://www.ats.ucla.edu/stat/papers/
=> Add curated statistics papers list by IDRE in UCLA

README.md
A great resource for practical statistics. A little on the engineering side of things but nice resource nonetheless.
Source: https://itl.nist.gov/div898/handbook/index.htm
=> Add NIST Handbook of Statistical Methods

README.md
You may want to change the order of the link, if you think it's better.
=> Added a link under "general resources" to a Github page with links about "understanding math"

README.md
Introduces the reader to most branches of mathematics.
=> Mathematics for Computer Science

README.md
Great book for beginners. Written as a relatively free-flowing dialogue between the AUTHOR and the READER.
=> Added a classic introductory calculus book & a blog.

README.md
a couple of introductions and two that show the application of surreal numbers to games
=> add surreal numbers, under foundations of mathematics

README.md
=> Add two new free books on Trigonometry and Algebra

README.md
So far I've added 22 of them, I'm just keeping this open so people can see and potentially tell me where i can improve.
=> adding books from george cain's website (issue #26)

README.md
Comprehensive collection of concepts.
=> Added a blog relevant in K-12 system

README.md
Also fixed a small typographical mistake for _The Joy of Cats_.
=> Add 7 Sketches to category theory

README.md
I'm not entirely sure that it belongs under algebraic geometry, but I thought it was the best fit.
=> Add the stacks project

README.md
=> Added few resources

README.md
A section on youtube series with important and significant lecture series on math.
=> Added a section on youtube Series.

README.md
Added Linear algebra resource. http://immersivemath.com/ila/index.html#
=> Added Linear algebra resource

README.md
added David M. Burton's "Elementary Number Theory"
=> added book for Number Theory

README.md
Added a link to a list of math textbooks
=> Add textbooks

README.md
Added _transition to pure rigour math_ section, and included the freely available _book of proof_ book
=> Hammack's book of proof

README.md
added _Students Lecture Notes_ section with two items beneath it
=> Students Lecture Notes

README.md
Added a new Topology resource and fixed Michael Taylor's Introduction to Complex Analysis link.
Closed older pull request to fix a typo.
=> Added new link & fixed crashed link

README.md
Added calculus.org as a learning platform for all things calculus
=> New general resource

README.md
Not sure if there are any limits on self-promotion on this list, I am the founder of Free Math, but the site is completely open source. It has been used by tens of thousands of students for distance learning since the start of the pandemic forcing everyone to go remote.
=> Add freemathapp.org

README.md
The lecture note's by Crane is an excellent resource for algorithm-minded CS students who want to learn discrete differential geometry with hands-on exercises on various topics. I also found the explanation very reader-friendly for the non-math audience.
=> add Crane's lecture notes on differential geometry

README.md
I'm not entirely sure who the authors of these are. The website lists Bart Snapp and Jim Fowler as developers of the project.
=> Add ximera interactive calculus books

README.md
Current link was dead. Quick google search lead me to the proposal:
- https://ksda.ccny.cuny.edu/PostedPapers/rickksda1107.pdf
=> Update Churchill's Algebraic Geometry

README.md
dzdx.xyz provides solutions to math problems using guiding questions.
The method is inspired by George Polya’s book «How to solve it».
It currently contains exercises on:
— Factorization
— Simplification of rational fractions
— Math induction
— Simplification of expression with roots and logarithms
=> Add dzdx.xyz to the Learning Platforms section

README.md
This channel is definitely awesome. Great topics, great presentation, for beginners and advanced mathematicians.
=> youtube: add Mathologer

README.md
xhub is a Chrome browser extension (which I wrote) that allows you to use math in GitHub pages (README, issues, PRs etc.). _Tools_ is probably th fitting section here.
=> tools: add xhub

README.md
Added the book `Computability - An introduction to recursive function theory` By Nigel Cutland. This is one of the most classic books to get student familiarized with the topic of recursive functions and computability in general. I read the book while doing my MSc in Math at the London School of Economics.
=> Added Computability - Nigel Cutland book

README.md
Updated students lecture notes, adding _Fabrice Baudoin_, and changing the title to _Researchers lecture notes_, As he is a professor
=> Fabrice Baudoin, Students Lecture Notes

README.md
[The Math District](https://www.youtube.com/TheMathDistrict) is a YouTube channel with lecture videos on a variety of mathematics topics, as well as tips for learning math.
=> Added "The Math District" to the YouTube section

README.md
added _related awesome lists_.
=> Related Awesome Lists

README.md
Can be found at https://oeis.org
Refs: #105
=> Add On-Line Encyclopedia of Integer Sequences

README.md
Lectures In Basic Computational Numerical Analysis
=> fix dead link in numerical analysis

README.md
Hi Rossant,
Changes in this PR:
- Add icon to symbolize paid resources (i.e., not free-of-charge resources) and short note at the top saying that the resources listed in this README are free except when denoted with the 💲icon.
- Add three books which are:
**Encyclopedia**
...
* 💲 [The Princeton Companion to Mathematics](https://press.princeton.edu/books/hardcover/9780691118802/the-princeton-companion-to-mathematics) - Timothy Gowers (Professor, Fields medallist), June Barrow-Green (Professor), and Imre Leader (Professor).
* 💲 [Encyclopedia of Distances (4th Edition)](https://link.springer.com/book/10.1007/978-3-662-52844-0) - Michel Marie Deza, Elena Deza.
**Transition To Pure Rigour Math**
...
* 📖💲 [How to Prove It: A Structured Approach (3rd …
=> Add paid resource icon💲 and three books.

README.md
Linear Algebra in name but mostly applications in numerical analysis, derivation of numerical algorithms, etc. Comes with video clips by topic and homework problems with hints and solutions.
=> add <Advanced Linear Algebra: Foundations to Frontiers>

README.md
Added [Mathcheap](mathcheap.xyz), A dead simple online LaTeX equation editor.
.
=> Added Mathcheap.xyz

README.md
There is a free PDF version for the book on Internet Archive
=> Use free PDF link for How to Prove It

README.md
I thought MathsJam looked a bit lonely in the new section, so I added one meeting (TMiP) that I've enjoyed and another (Bridges) that I've heard excellent things about.
=> Add meetings and conference section

README.md
Super engaging/encouraging math professor who collects vintage math books and reviews them. Also has classes on Udemy, etc
=> Add Youtube page of "The Math Sorcerer"

README.md
The link to book of proof is moving. 
See message on https://www.people.vcu.edu/~rhammack/BookOfProof/
=> fix: correcting the link of book of proof.

README.md
The 4th edition of [Linear Algebra Done Right](https://linear.axler.net/) by Sheldon Axler is Open Access.
=> Add Linear Algebra Done Right
